#https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

# #skip_macro_invocations=*
# binop_separator="Front"
# blank_lines_lower_bound=0
# blank_lines_upper_bound=1
# brace_style="SameLineWhere"
# color="Auto"
# combine_control_expr=true
# comment_width=80
# condense_wildcard_suffixes=true
# control_brace_style="AlwaysSameLine"
# empty_item_single_line=false
# enum_discrim_align_threshold=50
# fn_single_line=false
# force_multiline_blocks=false
# format_code_in_doc_comments=true
# format_macro_bodies=true
# format_macro_matchers=false
# format_strings=true
# group_imports="StdExternalCrate"
# hex_literal_case="Preserve"
# ignore=[]
# imports_granularity="Preserve"
# imports_indent="Visual"
# imports_layout="Mixed"
# indent_style="Visual"
# inline_attribute_width=150
# match_arm_blocks=false
# overflow_delimited_expr=true
# reorder_impl_items=false
# show_parse_errors=true
# space_after_colon=false
# space_before_colon=true
# spaces_around_ranges=true
# struct_field_align_threshold=25
# struct_lit_single_line=true
# trailing_comma="Always"
# trailing_semicolon=false
# type_punctuation_density="Compressed"
# unstable_features=true
# where_single_line=false
# wrap_comments=true

array_width=60
attr_fn_like_width=70
chain_width=60
disable_all_formatting=false
fn_call_width=60
fn_params_layout="Tall"
hard_tabs=false
match_arm_leading_pipes="Always"
match_block_trailing_comma=true
merge_derives=false
newline_style="Auto"
remove_nested_parens=true
reorder_imports=false
reorder_modules=false
short_array_element_width_threshold=25
single_line_if_else_max_width=75
single_line_let_else_max_width=75
struct_lit_width=25
struct_variant_width=35
tab_spaces=4
use_field_init_shorthand=false
use_small_heuristics="Off"
use_try_shorthand=true
